FROM eclipse-temurin:17-jdk

WORKDIR /opt

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --branch v4.0.0 --depth 1 \
    https://github.com/synthetichealth/synthea.git

WORKDIR /opt/synthea

ENTRYPOINT ["./run_synthea"]
