services:
  postgres:
    image: postgres:17
    container_name: healthcare_postgres

    environment:
      POSTGRES_USER: healthcare
      POSTGRES_PASSWORD: healthcare
      POSTGRES_DB: healthcare_analytics

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthcare -d healthcare_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    working_dir: /usr/app/dbt
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      postgres:
        condition: service_healthy
    
  synthea:
    build:
      context: .
      dockerfile: Dockerfile.synthea
    
    volumes:
      - ./data/raw/synthea:/output
      - ./synthea.properties:/opt/synthea/synthea-local.properties:ro

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile.ingestion

    working_dir: /usr/app

    volumes:
      - ./ingestion:/usr/app/ingestion:ro
      - ./data/raw/synthea:/usr/app/data/raw/synthea:ro
    
    environment: 
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: healthcare_analytics
      POSTGRES_USER: healthcare
      POSTGRES_PASSSWORD: healthcare

    depends_on: 
      postgres:
        condition: service_healthy

volumes:
  postgres_data: