services:
  postgres:
    image: postgres:17
    container_name: healthcare_postgres

    environment:
      POSTGRES_USER: healthcare
      POSTGRES_PASSWORD: healthcare
      POSTGRES_DB: healthcare_analytics

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthcare -d healthcare_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    working_dir: /usr/app/dbt
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: