exporter.csv.export = true
exporter.fhir.export = false
exporter.ccda.export = false

exporter.baseDirectory = /output
exporter.csv.append_mode = false
exporter.csv.folder_per_run = false

exporter.csv.included_files = patients.csv,encounters.csv,claims.csv,claims_transactions.csv,conditions.csv,procedures.csv,providers.csv,organizations.csv,payers.csv,payer_transitions.csv
